# Generated by Django 4.0.10 on 2024-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_patient', models.ImageField(null=True, upload_to='Photo_patients')),
                ('nom_patient', models.CharField(max_length=80)),
                ('prenom_patient', models.CharField(max_length=80)),
                ('date_nais_pat', models.DateField(null=True)),
                ('age_patient', models.IntegerField()),
                ('sexe_patient', models.CharField(max_length=1)),
                ('adresse_patient', models.CharField(max_length=100)),
                ('tel_patient', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patient',
            },
        ),
    ]
