# Generated by Django 3.2.5 on 2024-07-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('save_employer', '0003_remove_service_responsable_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('jour_arrive', models.DateTimeField()),
                ('jour_sorti', models.DateTimeField()),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_employer.employer')),
            ],
            options={
                'verbose_name': 'Soin',
                'verbose_name_plural': 'Soins',
                'db_table': 'Soin',
            },
        ),
    ]
