# Generated by Django 4.0.10 on 2024-07-02 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_batiment', models.ImageField(default=None, null=True, upload_to='./infrastructure/batiment')),
                ('nom_batiment', models.CharField(max_length=100)),
                ('nombre_niveau', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Batiment',
                'verbose_name_plural': 'Batiments',
                'db_table': 'Batiment',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_equip', models.ImageField(default=None, null=True, upload_to='./infrastructure/equipement')),
                ('nom_equipement', models.CharField(max_length=100)),
                ('type_equipement', models.CharField(max_length=100)),
                ('role_equipement', models.TextField()),
            ],
            options={
                'verbose_name': 'Equipement',
                'verbose_name_plural': 'Equipements',
                'db_table': 'Equipement',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_salle', models.IntegerField()),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Save.batiment')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'db_table': 'Niveau',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_salle', models.ImageField(default=None, null=True, upload_to='./infrastructure/salle')),
                ('nom_salle', models.CharField(max_length=100)),
                ('type_salle', models.CharField(max_length=100)),
                ('niveau_salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Save.niveau')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Posseder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_arrive', models.DateTimeField()),
                ('jour_sorti', models.DateTimeField(null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Save.equipement')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Save.salle')),
            ],
            options={
                'verbose_name': 'Posseder',
                'verbose_name_plural': 'Posseders',
                'db_table': 'Posseder',
                'unique_together': {('salle', 'equipement', 'jour_arrive', 'jour_sorti')},
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='salle_equipement',
            field=models.ManyToManyField(through='Save.Posseder', to='Save.salle'),
        ),
    ]
