# Generated by Django 3.2.5 on 2024-07-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('save_patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_employer', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'Employer',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100, null=True)),
                ('type_service', models.CharField(max_length=100)),
                ('patient', models.ManyToManyField(null=True, to='save_patient.Patient')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Travailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('jour_service', models.DateField()),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_patient.employer')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_patient.service')),
            ],
            options={
                'db_table': 'Travailler',
                'unique_together': {('id_employer', 'id_service', 'heure_debut', 'heure_fin', 'jour_service')},
            },
        ),
        migrations.CreateModel(
            name='OccupationSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salle_id', models.IntegerField()),
                ('jour_arrive', models.DateTimeField()),
                ('jour_sorti', models.DateTimeField(null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_patient.patient')),
            ],
            options={
                'verbose_name': 'Occupation',
                'verbose_name_plural': 'Occupations',
                'db_table': 'Occupation',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.IntegerField(default=0)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('date_fact', models.DateField(auto_now_add=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_patient.patient')),
                ('service_fact', models.ManyToManyField(to='care_patient.Service')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'Facture',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='travail',
            field=models.ManyToManyField(through='care_patient.Travailler', to='care_patient.Service'),
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel_rdv', models.IntegerField()),
                ('jour_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('patient_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_patient.patient')),
            ],
            options={
                'db_table': 'RendezVous',
                'unique_together': {('patient_rdv', 'personel_rdv', 'jour_rdv', 'heure_rdv')},
            },
        ),
    ]
