# Generated by Django 4.0.10 on 2024-06-25 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('save_patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employer', models.CharField(max_length=100)),
                ('prenom_employer', models.CharField(max_length=100)),
                ('sexe_employer', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100, null=True)),
                ('adresse_employer', models.CharField(max_length=150)),
                ('tel_employer', models.CharField(max_length=13)),
                ('compte_employer', models.CharField(max_length=100, null=True)),
                ('salaire_employer', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('type_service', models.CharField(max_length=100)),
                ('patient', models.ManyToManyField(to='save_patient.patient')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='Travailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.DateTimeField()),
                ('heure_fin', models.DateTimeField()),
                ('jour_service', models.DateField()),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_patient.employer')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_patient.service')),
            ],
            options={
                'unique_together': {('id_employer', 'id_service', 'heure_debut', 'heure_fin', 'jour_service')},
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fact', models.IntegerField(default=0)),
                ('mode_paiement', models.CharField(max_length=20)),
                ('date_fact', models.DateField(auto_now_add=True)),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_patient.patient')),
                ('service_fact', models.ManyToManyField(to='care_patient.service')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'Facture',
            },
        ),
        migrations.AddField(
            model_name='employer',
            name='travail',
            field=models.ManyToManyField(through='care_patient.Travailler', to='care_patient.service'),
        ),
    ]
