# Generated by Django 4.0.10 on 2024-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_patient', '0001_initial'),
        ('care_patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='patient',
            field=models.ManyToManyField(null=True, to='save_patient.patient'),
        ),
    ]
