# Generated by Django 4.0.10 on 2024-07-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_patient', '0002_alter_service_nom_service_alter_service_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facture',
            table=None,
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
    ]
