# Generated by Django 4.0.10 on 2024-07-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save_patient', '0001_initial'),
        ('care_patient', '0003_alter_facture_table_alter_service_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='Employer',
        ),
        migrations.AlterModelTable(
            name='facture',
            table='Facture',
        ),
        migrations.AlterModelTable(
            name='service',
            table='Service',
        ),
        migrations.AlterModelTable(
            name='travailler',
            table='Travailler',
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personel_rdv', models.IntegerField()),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('patient_rdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_patient.patient')),
            ],
            options={
                'db_table': 'RendezVous',
                'unique_together': {('patient_rdv', 'personel_rdv', 'date_rdv', 'heure_rdv')},
            },
        ),
    ]
