# Generated by Django 4.0.10 on 2024-06-25 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('save_employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100)),
                ('type_service', models.CharField(max_length=100)),
                ('responsable_service', models.CharField(default='Inconnu', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'Service',
            },
        ),
        migrations.AlterModelTable(
            name='fonctionsemp',
            table='Fonction',
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_employer', models.CharField(max_length=100)),
                ('prenom_employer', models.CharField(max_length=100)),
                ('sexe_employer', models.CharField(max_length=100)),
                ('specialite', models.CharField(max_length=100, null=True)),
                ('adresse_employer', models.CharField(max_length=150)),
                ('tel_employer', models.CharField(max_length=13)),
                ('compte_employer', models.CharField(max_length=100, null=True)),
                ('salaire_employer', models.CharField(max_length=100, null=True)),
                ('fonction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='save_employer.fonctionsemp')),
                ('service', models.ManyToManyField(to='save_employer.service')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'Employer',
            },
        ),
    ]
